site:
  title: Home
  description: This site is a static web site generator for Git.
  keywords: gitsite, git, static web site, html
  theme: default
  language: en-US
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  root-path: /sas-guider
  # set cdn path:
  cdn-path: https://cdn.jsdelivr.net/npm
  navigation:
    - title: 导航
      uri: /books/00-Nav/index.html
    #- title: Guidance
    #  uri: /books/00-Guidance/index.html
    #- title: SAS
    #  uri: /books/01-SAS/index.html
    #- title: Statistics
    #  uri: /books/02-Statistics/index.html
    #- title: CDISC
    #  uri: /books/03-CDISC/index.html
    # - title: XML
    #   uri: /books/04-XML/index.html
    # - title: BAT
    #   uri: /books/05-BAT/index.html
    # - title: VB
    #   uri: /books/06-VB/index.html
    # - title: Python
    #   uri: /books/07-Python/index.html
    # - title: R
    #   uri: /books/08-R/index.html
    - title: Blogs
      uri: /blogs/tech/index.html
    - title: License
      uri: /pages/license/index.html
    # - title: Q&A
    #  uri: https://github.com/goodlucker/sas-guider/discussions
    #  external: true
  git:
  base-url: https://github.com/goodlucker/sas-guider/blob/main/source
  contact:
    name: Rick
    github: https://github.com/goodlucker/sas-guider
    twitter: https://twitter.com/goodlucker
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    show 'Edit in Git':
    # display-git-link: true
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: disqus
      name: goodlucker
    analytics:
      provider: google
      gtag: G-5Z40K7NBL5

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt
# you can add any items:
